# admin/config.yml

backend:
  name: github
  repo: tyln141/azt-medikal-website # <-- DOĞRUSU BU ŞEKİLDE
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Sayfa İçerikleri"
    files:
      - file: "index.html"
        label: "Anasayfa"
        name: "index"
        fields:
          - {label: "Ana Başlık", name: "hero_title", widget: "string"}
          - {label: "Ana Alt Başlık", name: "hero_subtitle", widget: "string"}
          - {label: "Hakkımızda Başlığı", name: "about_title", widget: "string"}
          - {label: "Hakkımızda Metni", name: "about_text", widget: "markdown"}
          - {label: "Hakkımızda Resmi", name: "about_image", widget: "image"}
          - {label: "Ürünler Bölümü Başlığı", name: "products_title", widget: "string"}

  - name: "products"
    label: "Ürün Detay Sayfaları"
    files:
      - file: "urun-detay-1.html"
        label: "Ürün Detay: Hemodiyaliz Kateterleri"
        name: "product_1"
        fields:
          - {label: "Ürün Sayfa Başlığı", name: "title", widget: "string"}
          - {label: "Ürün Sayfa Resmi", name: "image", widget: "image"}
          - {label: "Ürün Sayfa Açıklaması", name: "description", widget: "text"}

      - file: "urun-detay-2.html"
        label: "Ürün Detay: İnfüzyon Pompaları"
        name: "product_2"
        fields:
          - {label: "Ürün Sayfa Başlığı", name: "title", widget: "string"}
          - {label: "Ürün Sayfa Resmi", name: "image", widget: "image"}
          - {label: "Ürün Sayfa Açıklaması", name: "description", widget: "text"}

      - file: "urun-detay-3.html"
        label: "Ürün Detay: Diyaliz Sarf Malzemeleri"
        name: "product_3"
        fields:
          - {label: "Ürün Sayfa Başlığı", name: "title", widget: "string"}
          - {label: "Ürün Sayfa Resmi", name: "image", widget: "image"}
          - {label: "Ürün Sayfa Açıklaması", name: "description", widget: "text"}

      - file: "urun-detay-4.html"
        label: "Ürün Detay: Port İğneleri"
        name: "product_4"
        fields:
          - {label: "Ürün Sayfa Başlığı", name: "title", widget: "string"}
          - {label: "Ürün Sayfa Resmi", name: "image", widget: "image"}
          - {label: "Ürün Sayfa Açıklaması", name: "description", widget: "text"}