backend:
  name: github
  repo: tyln141/azt-medikal-website
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "site_data"
    label: "Site Ayarları"
    files:
      - file: "data/content.json"
        label: "Tüm Site İçerikleri"
        name: "content"
        fields:
          - label: "Anasayfa"
            name: "homepage"
            widget: "object"
            fields:
              - {label: "Giriş Ana Başlık", name: "hero_title", widget: "string"}
              - {label: "Giriş Alt Başlık", name: "hero_subtitle", widget: "string"}
              - {label: "Hakkımızda Başlığı", name: "about_title", widget: "string"}
              - {label: "Hakkımızda Metni", name: "about_text", widget: "text"}
              - {label: "Hakkımızda Stat 1 Sayı", name: "about_stat1_number", widget: "string"}
              - {label: "Hakkımızda Stat 1 Metin", name: "about_stat1_text", widget: "string"}
              - {label: "Hakkımızda Stat 2 Sayı", name: "about_stat2_number", widget: "string"}
              - {label: "Hakkımızda Stat 2 Metin", name: "about_stat2_text", widget: "string"}
              - {label: "Hakkımızda Stat 3 Sayı", name: "about_stat3_number", widget: "string"}
              - {label: "Hakkımızda Stat 3 Metin", name: "about_stat3_text", widget: "string"}
              - {label: "Hakkımızda Logo/Resim", name: "about_image", widget: "image"}
              - {label: "Ürünler Bölümü Başlığı", name: "products_section_title", widget: "string"}
              - {label: "Neden Biz Bölümü Başlığı", name: "why_us_section_title", widget: "string"}
              - {label: "Neden Biz - Kart 1 Başlık", name: "why_us_card1_title", widget: "string"}
              - {label: "Neden Biz - Kart 1 Metin", name: "why_us_card1_text", widget: "text"}
              - {label: "Neden Biz - Kart 2 Başlık", name: "why_us_card2_title", widget: "string"}
              - {label: "Neden Biz - Kart 2 Metin", name: "why_us_card2_text", widget: "text"}
              - {label: "Neden Biz - Kart 3 Başlık", name: "why_us_card3_title", widget: "string"}
              - {label: "Neden Biz - Kart 3 Metin", name: "why_us_card3_text", widget: "text"}
              - {label: "Neden Biz - Kart 4 Başlık", name: "why_us_card4_title", widget: "string"}
              - {label: "Neden Biz - Kart 4 Metin", name: "why_us_card4_text", widget: "text"}
          - label: "Ürünler (Anasayfa)"
            name: "products"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "hidden"}
              - {label: "Başlık", name: "title", widget: "string"}
              - {label: "Kısa Açıklama", name: "description", widget: "string"}
              - {label: "Resim", name: "image", widget: "image"}
              - {label: "Ürün Sayfası Linki", name: "page_url", widget: "string"}